const DEMO_NOW = new Date('2026-09-15T14:30:00+01:00');
const money = new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0});
const hours = ms => Math.max(0, ms / 36e5);
const days = ms => Math.max(0, ms / 864e5);
const ageLabel = d => { const h=hours(DEMO_NOW-new Date(d)); return h<1?`${Math.round(h*60)}m`:h<24?`${h.toFixed(1)}h`:`${(h/24).toFixed(1)}d`; };
const dateLabel = d => new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(d));

const jobs = [
{id:'J-1048',customer:'Riverside Dental Practice',service:'Heat Pump Inspection',status:'completed',owner:'James',sub:false,scheduledEnd:'2026-09-15T09:30:00+01:00',completedAt:'2026-09-15T09:42:00+01:00',invoiceStatus:'pending',value:295,handoverMissing:true,events:[['09:03','Engineer arrived'],['09:42','Job completed'],['10:04','Handover flagged incomplete']]},
{id:'J-1047',customer:'Northgate Retail Park',service:'PPM HVAC Visit',status:'completed',owner:'Alicia',sub:false,scheduledEnd:'2026-09-15T10:00:00+01:00',completedAt:'2026-09-15T10:12:00+01:00',invoiceStatus:'pending',value:480,handoverMissing:false,events:[['08:58','Engineer arrived'],['10:12','Job completed']]},
{id:'J-1046',customer:'Meridian Office Park',service:'Water Hygiene Monthly Visit',status:'completed',owner:'Martin',sub:false,scheduledEnd:'2026-09-15T10:45:00+01:00',completedAt:'2026-09-15T11:02:00+01:00',invoiceStatus:'pending',value:365,handoverMissing:false,events:[['09:20','Engineer arrived'],['11:02','Job completed'],['11:08','Compliance forms submitted']]},
{id:'J-1033',customer:'Hillside Care Centre',service:'Boiler Service',status:'completed',owner:'James',sub:false,scheduledEnd:'2026-09-10T13:00:00+01:00',completedAt:'2026-09-10T13:15:00+01:00',invoiceStatus:'pending',value:1380,handoverMissing:true,events:[['10 Sep','Job completed'],['12 Sep','Office chased job notes']]},
{id:'J-1038',customer:'Kingston Pharmacy Group',service:'AC Remedial Works',status:'completed',owner:'Alicia',sub:false,scheduledEnd:'2026-09-12T14:00:00+01:00',completedAt:'2026-09-12T14:10:00+01:00',invoiceStatus:'pending',value:940,handoverMissing:false,events:[['12 Sep','Job completed'],['14 Sep','Invoice still pending']]},
{id:'J-1041',customer:'Beacon Student Living',service:'Ventilation Repair',status:'completed',owner:'SUB · Apex M&E',sub:true,scheduledEnd:'2026-09-13T12:00:00+01:00',completedAt:'2026-09-13T13:10:00+01:00',invoiceStatus:'pending',value:310,handoverMissing:true,events:[['13 Sep','Subcontractor completed work'],['13 Sep','Photos missing']]},
{id:'J-1051',customer:'Central Foods Distribution',service:'Cold Room Breakdown',status:'in_progress',owner:'Martin',sub:false,scheduledEnd:'2026-09-15T12:30:00+01:00',completedAt:null,invoiceStatus:null,value:850,handoverMissing:false,events:[['11:04','Engineer en route'],['11:42','Work started']]},
{id:'J-1052',customer:'Arden House',service:'Emergency Lighting Test',status:'en_route',owner:'SUB · BrightSpark',sub:true,scheduledEnd:'2026-09-15T13:30:00+01:00',completedAt:null,invoiceStatus:null,value:420,handoverMissing:false,events:[['12:30','Job assigned'],['13:05','Subcontractor en route']]},
{id:'J-1053',customer:'Oakwood Medical Centre',service:'AHU Filter Change',status:'not_started',owner:'Alicia',sub:false,scheduledEnd:'2026-09-15T13:45:00+01:00',completedAt:null,invoiceStatus:null,value:260,handoverMissing:false,events:[['11:45','Job scheduled']]},
{id:'J-1054',customer:'Riverside Dental Practice',service:'Reactive Callout',status:'scheduled',owner:'James',sub:false,scheduledEnd:'2026-09-15T16:30:00+01:00',completedAt:null,invoiceStatus:null,value:520,handoverMissing:false,events:[['12:12','Job booked']]}
];

const sites=[
{id:'site-1',name:'C233 · Meridian Office Park, Block A',address:'14 Meridian Way, Manchester M1 4BT',assets:[['Tap / outlet','5th Floor WC · WHB 1'],['Tap / outlet','5th Floor WC · WHB 2'],['Tap / outlet','4th Floor WC · WHB (TMV)'],['Shower','Lower Mezz Shower 1'],['Luminaire','Main Stairwell · Luminaire 1'],['Luminaire','Main Stairwell · Luminaire 2']]},
{id:'site-2',name:'Arden House',address:'31 King Street, Manchester M2 6AA',assets:[['Luminaire','East Stairwell · L1'],['Luminaire','East Stairwell · L2'],['Luminaire','Reception · L3']]}
];
const formTypes=[
{id:'ft-water',name:'Water Temperatures',category:'Water Hygiene',frequency:'Monthly',reg:'L8 ACoP',active:true},
{id:'ft-shower',name:'Shower Head Disinfection',category:'Water Hygiene',frequency:'Quarterly',reg:'L8 ACoP',active:true},
{id:'ft-light',name:'Emergency Light Monthly Flash Test',category:'Emergency Lighting',frequency:'Monthly',reg:'BS 5266',active:true}
];
const templates=[
{name:'Monthly Water Hygiene Visit',forms:['Water Temperatures']},
{name:'Quarterly Water Hygiene Visit',forms:['Water Temperatures','Shower Head Disinfection']},
{name:'Emergency Light Monthly Test',forms:['Emergency Light Monthly Flash Test']}
];
const submissions=[
{job:'J-1046',site:'C233 · Meridian Office Park',form:'Water Temperatures',status:'completed',updated:'2026-09-15T11:08:00+01:00'},
{job:'J-1046',site:'C233 · Meridian Office Park',form:'Shower Head Disinfection',status:'not_started',updated:'2026-09-15T11:08:00+01:00'},
{job:'J-1052',site:'Arden House',form:'Emergency Light Monthly Flash Test',status:'not_started',updated:'2026-09-15T13:05:00+01:00'}
];

const schedulingExceptions=jobs.filter(j=>['in_progress','en_route','not_started'].includes(j.status)&&new Date(j.scheduledEnd)<DEMO_NOW).map(j=>({job:j,severity:hours(DEMO_NOW-new Date(j.scheduledEnd))>1?'critical':'high',risk:'Scheduling',message:`Planned finish ${ageLabel(j.scheduledEnd)} ago but job is ${j.status.replace('_',' ')}`,since:j.scheduledEnd}));
const handoverExceptions=jobs.filter(j=>j.handoverMissing).map(j=>({job:j,severity:days(DEMO_NOW-new Date(j.completedAt))>2?'critical':'high',risk:'Handover',message:'Completed job is missing required handover evidence',since:j.completedAt}));
const billingExceptions=jobs.filter(j=>j.status==='completed'&&j.invoiceStatus==='pending').map(j=>({job:j,severity:days(DEMO_NOW-new Date(j.completedAt))>=3?'critical':days(DEMO_NOW-new Date(j.completedAt))>=1?'high':'medium',risk:'Billing',message:`${money.format(j.value)} completed work not yet invoiced`,since:j.completedAt}));
const complianceExceptions=[
{job:jobs.find(j=>j.id==='J-1046'),severity:'high',risk:'Compliance',message:'Quarterly shower disinfection form not completed',since:'2026-09-15T11:08:00+01:00'},
{job:jobs.find(j=>j.id==='J-1052'),severity:'medium',risk:'Compliance',message:'Emergency lighting form still not started',since:'2026-09-15T13:05:00+01:00'}
];
const visibilityExceptions=jobs.filter(j=>j.status==='completed'&&j.events.length<2).map(j=>({job:j,severity:'medium',risk:'Visibility',message:'Low job-event visibility',since:j.completedAt}));
let exceptions=[...schedulingExceptions,...handoverExceptions,...billingExceptions,...complianceExceptions,...visibilityExceptions];
const sevRank={critical:4,high:3,medium:2,low:1}; exceptions.sort((a,b)=>sevRank[b.severity]-sevRank[a.severity]||new Date(a.since)-new Date(b.since));
const riskCounts=exceptions.reduce((m,e)=>(m[e.job.id]=(m[e.job.id]||0)+1,m),{});
const pendingWip=jobs.filter(j=>j.status==='completed'&&j.invoiceStatus==='pending');
const totalWip=pendingWip.reduce((s,j)=>s+j.value,0);
const avgWipAge=pendingWip.reduce((s,j)=>s+days(DEMO_NOW-new Date(j.completedAt)),0)/Math.max(1,pendingWip.length);
const oldestWip=Math.max(...pendingWip.map(j=>days(DEMO_NOW-new Date(j.completedAt))));
const bucketDefs=[['0–1d',0,1],['1–2d',1,2],['2–3d',2,3],['3d+',3,999]];
const buckets=bucketDefs.map(([label,min,max])=>({label,value:pendingWip.filter(j=>{const d=days(DEMO_NOW-new Date(j.completedAt));return d>=min&&d<max}).reduce((s,j)=>s+j.value,0)}));

const app=document.querySelector('#app');
const riskClass=r=>r.toLowerCase();
const sev=(s)=>`<span class="severity ${s}"><span class="sev-dot" style="background:${s==='critical'?'#c43b47':s==='high'?'#d05a32':s==='medium'?'#b7791f':'#178a5b'}"></span>${s[0].toUpperCase()+s.slice(1)}</span>`;
const riskBadge=r=>`<span class="risk ${riskClass(r)}">${r}</span>`;
const ownerBadge=j=>`<span class="badge ${j.sub?'sub':''}">${j.owner}</span>`;

function render(){
const critical=exceptions.filter(e=>e.severity==='critical').length;
const breached=schedulingExceptions.length; const atRisk=jobs.filter(j=>['in_progress','en_route'].includes(j.status)&&new Date(j.scheduledEnd)>=DEMO_NOW).length; const onTrack=jobs.length-breached-atRisk;
app.innerHTML=`<div class="shell">
<header class="topbar"><div class="brand"><div class="brandmark">V</div><div><h1>Ops Hub</h1><small>Director exception control · Apex Climate Services</small></div></div><div class="top-actions"><span class="pill live"><span class="dot"></span>LIVE · 14:30</span><span class="pill owner">Owner view</span></div></header>
<main>
<section class="hero"><div class="hero-copy"><div class="eyebrow">Owner control centre</div><h2>Know what needs intervention before the office starts chasing it.</h2><p>One view across scheduling, handovers, job visibility, billing and compliance. The dashboard focuses attention on exceptions instead of forcing management to inspect every job.</p><div class="director-qs"><div class="q"><b>01</b> Which jobs are slipping right now?</div><div class="q"><b>02</b> What completed work is still waiting to become cash?</div><div class="q"><b>03</b> Where is evidence, ownership or compliance incomplete?</div></div></div><div class="hero-side panel"><div><div class="eyebrow">Open exceptions</div><div class="metric-big">${exceptions.length}</div><div class="muted">${critical} critical · ${exceptions.filter(e=>e.severity==='high').length} high</div></div><div><div class="eyebrow">Schedule adherence</div><div class="metric-big">${onTrack} / ${jobs.length}</div><div class="muted">${atRisk} at risk · ${breached} breached</div></div></div></section>
<section class="kpis"><div class="kpi"><div class="label">Unbilled WIP</div><div class="value">${money.format(totalWip)}</div><div class="detail">Completed work awaiting invoice</div></div><div class="kpi"><div class="label">Avg unbilled age</div><div class="value">${avgWipAge.toFixed(1)}d</div><div class="detail">Oldest ${oldestWip.toFixed(1)}d</div></div><div class="kpi"><div class="label">Handover gaps</div><div class="value">${handoverExceptions.length}</div><div class="detail">Completed jobs missing evidence</div></div><div class="kpi"><div class="label">Compliance gaps</div><div class="value">${complianceExceptions.length}</div><div class="detail">Required forms incomplete</div></div><div class="kpi"><div class="label">Subcontractor jobs</div><div class="value">${jobs.filter(j=>j.sub).length}</div><div class="detail">Live cross-party coordination</div></div></section>
<section class="section panel"><div class="panel-head"><div><h3>Exception Dashboard</h3><p>One row per operational risk. Jobs with multiple risks are intentionally repeated.</p></div><div class="tabs"><button class="tab active" data-filter="All">All</button>${['Scheduling','Visibility','Handover','Billing','Compliance'].map(r=>`<button class="tab" data-filter="${r}">${r}</button>`).join('')}</div></div><div class="panel-body table-wrap"><table><thead><tr><th>Severity</th><th>Risk</th><th>Job</th><th>Exception</th><th>Owner</th><th>Age</th><th></th></tr></thead><tbody id="exceptionRows">${exceptionRows('All')}</tbody></table></div></section>
<section class="section panel"><div class="panel-head"><div><h3>All Jobs</h3><p>Cross-job visibility without opening the dispatch board.</p></div></div><div class="panel-body table-wrap"><table><thead><tr><th>Job</th><th>Customer</th><th>Status</th><th>Owner</th><th>Planned finish</th><th>Value</th><th>Risks</th><th></th></tr></thead><tbody>${jobs.map(j=>`<tr><td><b>${j.id}</b></td><td>${j.customer}<div class="muted" style="font-size:11px">${j.service}</div></td><td>${j.status.replace('_',' ')}</td><td>${ownerBadge(j)}</td><td>${dateLabel(j.scheduledEnd)}</td><td>${money.format(j.value)}</td><td><span class="badge">${riskCounts[j.id]||0} risk${(riskCounts[j.id]||0)===1?'':'s'}</span></td><td><button class="link" data-job="${j.id}">View</button></td></tr>`).join('')}</tbody></table></div></section>
<section class="section split"><div class="panel"><div class="panel-head"><div><h3>Job-to-Cash</h3><p>Age completed work from job completion, not invoice-stub creation.</p></div></div><div class="panel-body"><div class="buckets">${buckets.map(b=>`<div class="bucket"><small>${b.label}</small><strong>${money.format(b.value)}</strong><div class="bar"><span style="width:${totalWip?Math.max(5,b.value/totalWip*100):0}%"></span></div></div>`).join('')}</div><div style="margin-top:14px" class="muted">Average unbilled age <b style="color:var(--ink)">${avgWipAge.toFixed(1)} days</b> · oldest <b style="color:var(--ink)">${oldestWip.toFixed(1)} days</b>. Historical invoice cycle should be tracked separately from pending WIP age.</div></div></div><div class="panel"><div class="panel-head"><div><h3>Subcontractor Coordination</h3><p>External ownership and handover exposure.</p></div></div><div class="panel-body sub-grid">${jobs.filter(j=>j.sub).map(j=>`<div class="mini-card"><h4>${j.customer}</h4><div class="meta">${j.service}<br>${ownerBadge(j)} · ${j.status.replace('_',' ')}</div><div class="score">${riskCounts[j.id]||0} risks</div><button class="link" data-job="${j.id}" style="margin-top:7px">Open job</button></div>`).join('')}</div></div></section>
<section class="section panel"><div class="panel-head"><div><h3>FSM Risk Scorecard</h3><p>Management-level signal across the operational risk matrix.</p></div></div><div class="panel-body risk-grid">${riskCards()}</div></section>
<section class="section panel"><div class="panel-head"><div><h3>Compliance Control</h3><p>Office visibility over sites, assets, form catalogue, job templates and submissions.</p></div><span class="badge">New today</span></div><div class="panel-body"><div class="compliance-kpis"><div class="ckpi"><b>${sites.length}</b><span>Sites</span></div><div class="ckpi"><b>${sites.reduce((s,x)=>s+x.assets.length,0)}</b><span>Tracked assets</span></div><div class="ckpi"><b>${formTypes.length}</b><span>Form types</span></div><div class="ckpi"><b>${templates.length}</b><span>Job templates</span></div><div class="ckpi"><b>${submissions.filter(s=>s.status==='completed').length}/${submissions.length}</b><span>Forms completed</span></div></div><div class="compliance-grid">${sites.map(s=>`<div class="mini-card"><h4>${s.name}</h4><div class="meta">${s.address}</div><div class="score">${s.assets.length} assets</div><div class="recommend">${s.assets.slice(0,3).map(a=>`${a[0]} · ${a[1]}`).join('<br>')}${s.assets.length>3?'<br>…':''}</div></div>`).join('')}<div class="mini-card"><h4>Form catalogue</h4><div class="meta">${formTypes.map(f=>`${f.name} · ${f.frequency} · ${f.reg}`).join('<br>')}</div></div><div class="mini-card"><h4>Required submissions</h4><div class="meta">${submissions.map(s=>`${s.job} · ${s.form} · <b>${s.status.replace('_',' ')}</b>`).join('<br>')}</div></div></div></div></section>
</main></div><div class="drawer-backdrop" id="backdrop"><aside class="drawer"><div class="drawer-head"><div><div class="eyebrow">Job detail</div><h3 id="drawerTitle"></h3></div><button class="close" id="drawerClose">×</button></div><div class="drawer-body" id="drawerBody"></div></aside></div>`;
wire();
}
function exceptionRows(filter){const rows=exceptions.filter(e=>filter==='All'||e.risk===filter);return rows.length?rows.map(e=>`<tr><td>${sev(e.severity)}</td><td>${riskBadge(e.risk)}</td><td><b>${e.job.id}</b><div class="muted" style="font-size:11px">${e.job.customer}</div></td><td>${e.message}${riskCounts[e.job.id]>1?` <span class="badge">${riskCounts[e.job.id]} risks</span>`:''}</td><td>${ownerBadge(e.job)}</td><td>${ageLabel(e.since)}</td><td><button class="link" data-job="${e.job.id}">View</button></td></tr>`).join(''):`<tr><td colspan="7" class="empty">No exceptions in this category.</td></tr>`}
function riskCards(){const defs=[['Scheduling',schedulingExceptions.length,'Keep live schedule exceptions visible and owner-assigned.'],['Visibility',visibilityExceptions.length,'Maintain job-event coverage and live status.'],['Handover',handoverExceptions.length,'Require evidence before job close / invoice handoff.'],['Billing',billingExceptions.filter(x=>x.severity==='critical').length+billingExceptions.filter(x=>x.severity==='high').length,'Age WIP from completion and escalate over-threshold jobs.'],['Compliance',complianceExceptions.length,'Track required forms, failed checks and overdue submissions centrally.']];return defs.map(([name,count,rec])=>{const level=count>=3?'critical':count>=2?'high':count===1?'medium':'low';return `<div class="mini-card"><h4>${name}</h4><div class="score ${level}">${level.toUpperCase()}</div><div class="meta">${count} active exception${count===1?'':'s'}</div><div class="recommend">${rec}</div></div>`}).join('')}
function wire(){document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#exceptionRows').innerHTML=exceptionRows(b.dataset.filter);wireJobButtons();}));wireJobButtons();document.querySelector('#drawerClose').onclick=closeDrawer;document.querySelector('#backdrop').addEventListener('click',e=>{if(e.target.id==='backdrop')closeDrawer();});}
function wireJobButtons(){document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>openJob(b.dataset.job));}
function openJob(id){const j=jobs.find(x=>x.id===id);if(!j)return;document.querySelector('#drawerTitle').textContent=`${j.id} · ${j.customer}`;document.querySelector('#drawerBody').innerHTML=`<div class="detail-grid"><div class="detail"><span>Service</span><b>${j.service}</b></div><div class="detail"><span>Status</span><b>${j.status.replace('_',' ')}</b></div><div class="detail"><span>Owner</span><b>${j.owner}</b></div><div class="detail"><span>Value</span><b>${money.format(j.value)}</b></div><div class="detail"><span>Planned finish</span><b>${dateLabel(j.scheduledEnd)}</b></div><div class="detail"><span>Active risks</span><b>${riskCounts[j.id]||0}</b></div></div><div class="timeline">${j.events.map(e=>`<div class="event"><b>${e[1]}</b><span>${e[0]}</span></div>`).join('')}</div>`;document.querySelector('#backdrop').classList.add('open');}
function closeDrawer(){document.querySelector('#backdrop').classList.remove('open');}
render();
